select substring(sample_bk,1,position('_' in sample_bk)-1) as sample_bk, p.k as attr, p.v as val
from atacseq_bulk_metadata
join lateral(values
	 ('hubmap_subject_bk'                        ,hubmap_subject_bk                        )
	,('hubmap_tissue_bk'                         ,hubmap_tissue_bk                         )
	,('execution_datetime'                       ,execution_datetime                       )
	,('protocols_io_doi'                         ,protocols_io_doi                         )
	,('operator'                                 ,"operator"                               )
	,('operator_email'                           ,operator_email                           )
	,('pi'                                       ,pi                                       )
	,('pi_email'                                 ,pi_email                                 )
	,('assay_category'                           ,assay_category                           )
	,('assay_type'                               ,assay_type                               )
	,('analyte_class'                            ,analyte_class                            )
	,('is_targeted'                              ,is_targeted                              )
	,('acquisition_instrument_vendor'            ,acquisition_instrument_vendor            )
	,('acquisition_instrument_model'             ,acquisition_instrument_model             )
	,('is_technical_replicate'                   ,is_technical_replicate                   )
	,('library_id'                               ,library_id                               )
	,('bulk_atac_cell_isolation_protocols_io_doi',bulk_atac_cell_isolation_protocols_io_doi)
	,('nuclei_quality_metric'                    ,nuclei_quality_metric                    )
	,('bulk_transposition_input_number_nuclei'   ,bulk_transposition_input_number_nuclei   )
	,('transposition_method'                     ,transposition_method                     )
	,('transposition_transposase_source'         ,transposition_transposase_source         )
	,('transposition_kit_number'                 ,transposition_kit_number                 )
	,('library_construction_protocols_io_doi'    ,library_construction_protocols_io_doi    )
	,('library_layout'                           ,library_layout                           )
	,('library_adapter_sequence'                 ,library_adapter_sequence                 )
	,('library_pcr_cycles'                       ,library_pcr_cycles                       )
	,('library_average_fragment_size'            ,library_average_fragment_size            )
	,('library_creation_date'                    ,library_creation_date                    )
	,('sequencing_reagent_kit'                   ,sequencing_reagent_kit                   )
	,('sequencing_read_format'                   ,sequencing_read_format                   )
	,('sequencing_read_percent_q30'              ,sequencing_read_percent_q30              )
	,('sequencing_phix_percent'                  ,sequencing_phix_percent                  )
	,('library_final_yield_value'                ,library_final_yield_value                )
	,('library_final_yield_units'                ,library_final_yield_units                )
	,('library_preparation_kit'                  ,library_preparation_kit                  )
	,('library_concentration_value'              ,library_concentration_value              )
	,('library_concentration_unit'               ,library_concentration_unit               )
	,('metadata_path'                            ,metadata_path                            )
	,('data_path'                                ,data_path                                )
	,('fastq_file_size'                          ,fastq_file_size                          )
) p(k,v)
on p.v is not null
;
