create table staging.metadata_rnaseq_single_nucleus_addl
(experiment_date varchar(100)
,sample varchar(100)
,tissue_preservation_method varchar(100)
,tissue_location varchar(100)
,tissue_phenotype varchar(100)
,amt_used_mg varchar(100)
,protocol varchar(100)
,dissociation_method varchar(100)
,dissociation_buffer varchar(100)
,note varchar(100)
,snrnaseq varchar(100)
,yield varchar(100)
,target_recovery_and_10x_cell_concentration varchar(100)
,cdna_conc varchar(100)
,kit_version_10x varchar(100)
,sequencing_submission varchar(100)
,sequencing_parameters varchar(100)
,pass_qc varchar(100)
,snrnaseq_library_created varchar(100)
,snrnaseq_library_sequenced varchar(100)
,snrnaseq_data_quality varchar(100)
,snatacseq varchar(100)
,snatacseq_library_created varchar(100)
,snatacseq_library_sequenced varchar(100)
,snatacseq_data_quality varchar(100))
;
