create table staging.metadata_atacseq_bulk_hiseq
(sample_id varchar(100)
,donor_id varchar(100)
,tissue_id varchar(100)
,execution_datetime varchar(100)
,protocols_io_doi varchar(100)
,operator varchar(100)
,operator_email varchar(100)
,pi varchar(100)
,pi_email varchar(100)
,assay_category varchar(100)
,assay_type varchar(100)
,analyte_class varchar(100)
,is_targeted varchar(100)
,acquisition_instrument_vendor varchar(100)
,acquisition_instrument_model varchar(100)
,is_technical_replicate varchar(100)
,library_id varchar(100)
,bulk_atac_cell_isolation_protocols_io_doi varchar(100)
,nuclei_quality_metric varchar(100)
,bulk_transposition_input_number_nuclei varchar(100)
,transposition_method varchar(100)
,transposition_transposase_source varchar(100)
,transposition_kit_number varchar(100)
,library_construction_protocols_io_doi varchar(100)
,library_layout varchar(100)
,library_adapter_sequence varchar(200)
,library_pcr_cycles varchar(100)
,library_average_fragment_size varchar(100)
,library_creation_date varchar(100)
,sequencing_reagent_kit varchar(100)
,sequencing_read_format varchar(100)
,sequencing_read_percent_q30 varchar(100)
,sequencing_phix_percent varchar(100)
,library_final_yield_value varchar(100)
,library_final_yield_units varchar(100)
,library_preparation_kit varchar(100)
,library_concentration_value varchar(100)
,library_concentration_unit varchar(100)
,metadata_path varchar(100)
,data_path varchar(100)
,fastqfilesize varchar(100))
;
--"sample_id" is a misnomer: this is really a duplicate of the "library ID" or
--"technical replicate ID" in column "library_id". The data has a format of,
--e.g. "B001-A-401_A", so it does include the internal sample ID, albeit with
--an "_A" or "_B" tag. I am including this column in order not to have to
--manually drop its column from the metadata.tsv file and because the portion of
--it up to the underscore is used to join to core.sample for the foreign key
--reference when the tables are loaded.
